[pytest]
markers =
    smoke: 冒烟测试用例
; 其他常用配置（可取消注释启用）:
; testpaths = testcase
; python_files = test_*.py
; python_classes = Test*
; python_functions = test_*
; addopts = -s --alluredir=allure-result
